<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CoreAdmin_ERP</RootNamespace>
    <UserSecretsId>be0c05f2-c79d-4ca3-899e-d132f032689d</UserSecretsId>
  </PropertyGroup>

</Project>
